# Generated by Django 5.2.4 on 2025-07-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('html_content', models.TextField()),
                ('docx_file', models.FileField(upload_to='docx/')),
                ('pdf_file', models.FileField(upload_to='pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
